### ISSUE TITLE
Is it possible to add the stoneblock 3 modpack?

### ISSUE THREAD

**Issue by thekhao** [PojavLauncherTeam/pojavlauncherteam.github.io#101]
I have a stoneblock 3 survival with some buddies that I'd like to join with my tel which only has 2g of ram. I've tried to install it but can't figure out how. Would it be possible to add it to pojavlauncher's modpack category?

**Comment by GaucovyAero** [comment]
wrong repo, go to pojavlauncherteam/pojavlauncher instead
