### ISSUE TITLE
Crash again and again after trying to join any world 

### ISSUE THREAD

**Issue by FAIZANYT** [PojavLauncherTeam/pojavlauncherteam.github.io#103]
---- Minecraft Crash Report ---- // This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~] Time: 2023-10-24 18:39:53 Description: Loading NBT data java.util.zip.ZipException: invalid distance too far back 	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) 	at java.base/java.io.DataInputStream.readFully(Unknown Source) 	at java.base/java.io.DataInputStream.readLong(Unknown Source) 	at net.minecraft.class_2501$1.method_23250(class_2501.java:30) 	at net.minecraft.class_2501$1.method_23262(class_2501.java:21) 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2499$1.method_23249(class_2499.java:43) 	at net.minecraft.class_2499$1.method_23262(class_2499.java:26) 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2507.method_10626(class_2507.java:147) 	at net.minecraft.class_2507.method_10625(class_2507.java:91) 	at net.minecraft.class_2507.method_10627(class_2507.java:87) 	at net.minecraft.class_2867.method_17911(class_2867.java:57) 	at net.minecraft.class_4698.method_27943(class_4698.java:186) 	at net.minecraft.class_4698.method_27939(class_4698.java:236) 	at net.minecraft.class_3847$class_3907.run(class_3847.java:60) 	at net.minecraft.class_3846.method_16907(class_3846.java:91) 	at net.minecraft.class_3846.method_16900(class_3846.java:146) 	at net.minecraft.class_3846.run(class_3846.java:102) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 	at java.base/java.lang.Thread.run(Unknown Source) A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Server thread Stacktrace: 	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) 	at java.base/java.io.DataInputStream.readFully(Unknown Source) 	at java.base/java.io.DataInputStream.readLong(Unknown Source) 	at net.minecraft.class_2501$1.method_23250(class_2501.java:30) 	at net.minecraft.class_2501$1.method_23262(class_2501.java:21) 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2499$1.method_23249(class_2499.java:43) 	at net.minecraft.class_2499$1.method_23262(class_2499.java:26) 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2507.method_10626(class_2507.java:147) 	at net.minecraft.class_2507.method_10625(class_2507.java:91) 	at net.minecraft.class_2507.method_10627(class_2507.java:87) 	at net.minecraft.class_2867.method_17911(class_2867.java:57) 	at net.minecraft.class_4698.method_27943(class_4698.java:186) 	at net.minecraft.class_4698.method_27939(class_4698.java:236) 	at net.minecraft.class_3847$class_3907.run(class_3847.java:60) 	at net.minecraft.class_3846.method_16907(class_3846.java:91) 	at net.minecraft.class_3846.method_16900(class_3846.java:146) -- NBT Tag -- Details: 	Tag name: data 	Tag type: LONG[] Stacktrace: 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2499$1.method_23249(class_2499.java:43) 	at net.minecraft.class_2499$1.method_23262(class_2499.java:26) 	at net.minecraft.class_2487.method_10581(class_2487.java:500) 	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) 	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) 	at net.minecraft.class_2507.method_10626(class_2507.java:147) 	at net.minecraft.class_2507.method_10625(class_2507.java:91) 	at net.minecraft.class_2507.method_10627(class_2507.java:87) 	at net.minecraft.class_2867.method_17911(class_2867.java:57) 	at net.minecraft.class_4698.method_27943(class_4698.java:186) 	at net.minecraft.class_4698.method_27939(class_4698.java:236) 	at net.minecraft.class_3847$class_3907.run(class_3847.java:60) 	at net.minecraft.class_3846.method_16907(class_3846.java:91) 	at net.minecraft.class_3846.method_16900(class_3846.java:146) 	at net.minecraft.class_3846.run(class_3846.java:102) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 	at java.base/java.lang.Thread.run(Unknown Source) -- Wrapped in -- Details: 	Wrapping exception: ~~ERROR~~ CompletionException: net.minecraft.class_148: Loading NBT data Stacktrace: 	at net.minecraft.server.MinecraftServer.method_40376(MinecraftServer.java:729) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) 	at java.base/java.lang.Thread.run(Unknown Source) -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Linux (aarch64) version Android-12 	Java Version: 17.0.9-internal, N/A 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 426553344 bytes (406 MiB) / 1203765248 bytes (1148 MiB) up to 1203765248 bytes (1148 MiB) 	CPUs: 8 	Processor Vendor: 0x51 	Processor Name: AArch64 Processor rev 2 (aarch64) 	Identifier: 0x51 Family 8 Model 0x800 Stepping r10p4 	Microarchitecture: unknown 	Frequency (GHz): -0.00 	Number of physical packages: 2 	Number of physical CPUs: 8 	Number of logical CPUs: 8 	Graphics card #0 name: unknown 	Graphics card #0 vendor: unknown 	Graphics card #0 VRAM (MB): 0.00 	Graphics card #0 deviceId: unknown 	Graphics card #0 versionInfo: unknown 	Virtual memory max (MB): 4108.66 	Virtual memory used (MB): 5048.33 	Swap memory total (MB): 2252.00 	Swap memory used (MB): 1729.20 	JVM Flags: 3 total; -Xms1148M -Xmx1148M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar 	Fabric Mods: 		alternate-current: Alternate Current 1.7.0 		appleskin: AppleSkin 2.5.1+mc1.20 		architectury: Architectury 9.1.12 		boostedbrightness: Boosted Brightness 2.2.0 		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.97 			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.97 			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.97 			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.97 			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.97 			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.97 			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.97 			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.97 			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.97 			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.97 			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.97 			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.97 			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.97 			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.97 			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.97 			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.97 			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.97 			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.97 			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.97 			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.97 			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.97 			com_electronwill_night-config_core: core 3.6.5 			com_electronwill_night-config_toml: toml 3.6.5 			com_ibm_async_asyncutil: asyncutil 0.1.0 			net_objecthunter_exp4j: exp4j 0.4.8 			org_threadly_threadly: threadly 7.0 		chat_heads: Chat Heads 0.10.22 		collective: Collective 6.65 		colormeoutlines: Color Me Outlines 1.1.2 		crystaloptimizer: CrystalOptimizer 1.0.0 		dark-loading-screen: Dark Loading Screen 1.6.14 		dashloader: DashLoader 5.0.0-beta.2+1.20.0 			com_github_luben_zstd-jni: zstd-jni 1.5.2-2 			dev_notalpha_taski: Taski 2.1.0 			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3 		dynamic_fps: Dynamic FPS 3.2.1 		easiervillagertrading: EasierVillagerTrading 1.20-fabric0.83.0-1.5.4 			gbfabrictools: GBfabrictools 1.3.5+1.20 		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1 		exordium: Exordium 1.2.1-mc1.20.1 			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.2 		fabric-api: Fabric API 0.90.4+1.20.1 			fabric-api-base: Fabric API Base 0.4.30+7abfd51577 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677 			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577 			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77 			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77 			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377 			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377 			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77 			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77 			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677 			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177 			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777 			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677 			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077 			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077 			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377 			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77 			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77 		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0 		fabric-skinmc: SkinMC Mod 1.20-1.0.0 		fabricloader: Fabric Loader 0.14.23 		fallingtree: FallingTree 4.3.0 		ferritecore: FerriteCore 6.0.1 		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.1.1 		freecam: Freecam 1.1.10+1.20 			cloth-config: Cloth Config v11 11.0.99 				cloth-basic-math: cloth-basic-math 0.6.1 		healthindicators: PlayerHealthIndicators 1.1.0 		ias: In-Game Account Switcher 8.0.2 		indium: Indium 1.0.27+mc1.20.1 		inventoryhud: Inventory HUD + 3.4.18 		iris: Iris 1.6.10 			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13 			org_anarres_jcpp: jcpp 1.4.14 			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1 		java: OpenJDK 64-Bit Server VM 17 		krypton: Krypton 0.2.3 			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT 		lambdynlights: LambDynamicLights 2.3.2+1.20.1 			pride: Pride Lib 1.2.0+1.19.4 			spruceui: SpruceUI 5.0.0+1.20 		lazydfu: LazyDFU 0.1.3 		lithium: Lithium 0.11.2 		mcwbridges: Macaw's Bridges 2.1.0 		mcwwindows: Macaw's Windows 2.2.0 		memoryleakfix: Memory Leak Fix 1.1.2 		minecraft: Minecraft 1.20.1 		modelfix: Model Gap Fix 1.14 		modmenu: Mod Menu 7.2.2 		morecosmetics: MoreCosmetics ${version} 		moreculling: More Culling 1.20.1-0.19.0 			conditional-mixin: conditional mixin 0.3.2 		namepain: Name Pain 1.5.2 		nohurtcamplus: NoHurtCam+ 2.3.1-1.20.1 		perspectivemod: Perspective Mod Redux 0.0.5_01 		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.1-build.95 		replaymod: Replay Mod 1.20.1-2.6.13 		shulkerboxtooltip: Shulker Box Tooltip 4.0.2+1.20 		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1 		skinswapper: Skin Swapper 3.1.4 			org_apache_httpcomponents_httpclient: httpclient 4.5.10 			org_apache_httpcomponents_httpcore: httpcore 4.4.12 			org_apache_httpcomponents_httpmime: httpmime 4.5.10 		sodium: Sodium 0.5.3 		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112 			caffeineconfig: CaffeineConfig 1.3.0+1.17 			crowdin-translate: CrowdinTranslate 1.4+1.19.3 		spark: spark 1.10.53 			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT 		starlight: Starlight 1.1.2+fabric.dbc156f 		ukulib: ukulib 1.0.0-beta.3+1.20.1 			com_moandjiezana_toml_toml4j: toml4j 0.7.2 			gs_mclo_java_mclogs-java: mclogs-java 2.1.1 		vmp: Very Many Players 0.2.0+beta.7.102 		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20 			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT 			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT 			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT 			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT 			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT 			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT 			org_quiltmc_parsers_gson: gson 0.2.1 			org_quiltmc_parsers_json: json 0.2.1 		zoomify: Zoomify 2.11.2 			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1 			dev_isxander_settxi_settxi-core: settxi-core 2.10.6 			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6 	Loaded Shaderpack: (off) 	NEC status: No NEC detected 	Server Running: true 	Player Count: 0 / 8; [] 	Data Packs: vanilla, bundle, fabric 	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla 	World Generation: Stable 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric' 	Launched Version: 1.20.1

**Comment by FAIZANYT** [comment]
Help me and please tell me what's the issue

**Comment by GaucovyAero** [comment]
wrong repo, go to pojavlauncherteam/pojavlauncher instead
