### ISSUE TITLE
Ingame chat Keyboard Layout from QWERTY to QWERTZ

### ISSUE THREAD

**Issue by Marvin732** [PojavLauncherTeam/pojavlauncherteam.github.io#104]
I am on Android 13 running Pojav Launcher.
A request that i have is, is it possible to add a keyboard layout change in the app?

I am using an external keyboard and mouse to play and writing commands like /gamemode creative are harder for me type in since the keyboard layout is different ingame than whats set in system.

**Comment by GaucovyAero** [comment]
changing the keyboard is a hardcoded shortcut in android, shift + space
