### ISSUE TITLE
Update TrollStore version support

### ISSUE THREAD

**Issue by CatsLover2006** [PojavLauncherTeam/pojavlauncherteam.github.io#113]
Apple f’d up CoreTrust a second time and now TrollStore works up to 16.6.1 and also on 17.0 specifically. Figured I’d let you guys know so someone can update that section of the guide.

**Comment by ItAnthon** [comment]
what guide are you talking about 

Also: there’s no TrollStore installation method for anything past 16.5 for arm64e devices.

**Comment by CatsLover2006** [comment]
Wiki -> Getting Started -> Installing the Launcher -> iOS
And that’s a good point but the error is still present

**Comment by ItAnthon** [comment]
ill go ahead and make a pull request and update the information, thanks for the suggestion!
