### ISSUE TITLE
No portrait support?

### ISSUE THREAD

**Issue by Jwjw120** [PojavLauncherTeam/pojavlauncherteam.github.io#124]
Not the biggest issue as it's definitely not a necessity but there doesn't seem to be any support for running the game in portrait mode. The menus work fine but when the game starts it rotates back to landscape, which is fine but for certain foldables (pixel fold & oppo find n2) I'm not able to use my controller unless it's in portrait, unless there's some jvm argument I'm missing or something

**Comment by GaucovyAero** [comment]
wrong repository, this is the website, go to pojavlauncherteam/pojavlauncher
