### ISSUE TITLE
Allow the app to access all files on Android

### ISSUE THREAD

**Issue by Enderteck** [PojavLauncherTeam/pojavlauncherteam.github.io#125]
I'd like to sync my worlds between PC And mobile but I can't put an instance in the documents folder for example. 

I don't want to root my tablet but I think if I could allow the app to access all files there might be a possibility. 

This would also make sharing modpacks easier and the usage of future mobile mod managers possible.

Thx in advance for your feedback.

Happy new year too !

**Comment by mchnjt** [comment]
Please move your issue to the [main repo](https://github.com/PojavLauncherTeam/PojavLauncher), assuming you're on Android.

**Comment by Enderteck** [comment]
Mb didn't realize when I clicked on the wiki website it was sending me here
