### ISSUE TITLE
Can't access custom controls menu in latest release.

### ISSUE THREAD

**Issue by kjkll** [PojavLauncherTeam/pojavlauncherteam.github.io#13]
I couldn't use my bluetooth kbd with the last release (had to double tap to get a keypress sent.)  Current release (as of 12/2/22) fixed that, so kudos.  Unfortunately, I can't save my cleaned-up-almost-button-free custom control setup now, because the swipe left-to-right menu don't appear when swoped.

A work around might be saving it over the top of my previous default?

Lenovo tab MH10, Android 10.

**Comment by GaucovyAero** [comment]
the swipe isnt a thing anymore, there is a cogwheel on the top of your screen that you can touch

**Comment by kjkll** [comment]
Sorry, but there is NO cog at the top of the screen, just the old 'swipe to get a menu' message.  Did I miss an update to the update?
