### ISSUE TITLE
invalid session try restarting your game or launcher 

### ISSUE THREAD

**Issue by Mesla7780** [PojavLauncherTeam/pojavlauncherteam.github.io#134]
every time I try to play with my friends with LAN online using VPN I get this error and I can't play (I know how to play by creating servers but where I create a server I can't put the mods I want)do you know how to solve ?

**Comment by Seblor** [comment]
[Please read the PSA](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/issues/73), you are in the wrong repository.

> We don't do handling of issues, suggestions, and improvements for the launcher itself in this repository.

**Comment by Mesla7780** [comment]
I'm sorry
