### ISSUE TITLE
[Suggestion] Be able to detect Pojav

### ISSUE THREAD

**Issue by WarnDa** [PojavLauncherTeam/pojavlauncherteam.github.io#136]
As a server owner, we sometimes want to control which player use Pojav or not, because they can bypass some things or be afk all the day without being kick just because they put the game on their phone.

So put the client brand to "Pojav" would solve this and allow server owner to verify.

**Comment by artdeell** [comment]
Nope, not going to do that. That would allow discrimination.

**Comment by ProJakob** [comment]
I don't see the difference of someone afking on their phone or computer, if you need to block afk players, make a plugin to detect afking methods, don't ban a group of players..
