### ISSUE TITLE
Suggestion: please allow to select other folders

### ISSUE THREAD

**Issue by tygoee** [PojavLauncherTeam/pojavlauncherteam.github.io#139]
As of a newer Android version (13?), Android restricted users from folder access to Android/data folders. It's now only meant to be accessible on desktop with USB and currently there are workarounds, but they're getting patched every update. This means that if we want to put in mods or recourcepacks into our .minecraft/ folder, it's not possible.

When trying to select another folder, there's no option besides the ones in the data folder:

![Screenshot_20240227_180632_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/assets/87303800/e59b3644-d1c0-4372-914d-bfec2779af03)

It would be nice to have a seperated button (at the top maybe) saying 'Internal storage' that leads to /data/emulated/0/

I don't know the codebase, but this should be a pretty small change. For accessing the storage you do need to prompt the user for MANAGE_EXTERNAL_STORAGE by the way

**Comment by artdeell** [comment]
The issue, as always, is Google: if we want to request that permission and still be on Google Play, we will need to be a file manager or have some other good reason to actually use it. And we don't reallly want to become a file manager.

**Comment by tygoee** [comment]
I don't think that would be a big issue, I've seen multiple apps having file permission just to import/export data, or select a json or csv file. I think that's read access only though.

A similar app with the permission is Aegis (2fa token vault), which stores backups on external storage every change (I don't see it listed in their app though, you might want to look into it?).

Google maybe won't reject if you explain the reason

Another way could be that there's a tab 'Manage Instances' where you can upload files or zipped folders anywhere, you won't need any additional permissions as you already can read files (for selecting jar files).

**Comment by tygoee** [comment]
I don't think that would be a big issue, I've seen multiple apps having file permission just to import/export data, or select a json or csv file. I think that's read access only though.

A similar app with the permission is Aegis (2fa token vault), which stores backups on external storage every change (I don't see it listed in their app though, you might want to look into it?).

Google maybe won't reject if you explain the reason

Another way could be that there's a tab 'Manage Instances' where you can upload files or zipped folders anywhere, you won't need any additional permissions as you already can read files (for selecting jar files).

**Comment by GaucovyAero** [comment]
please move this to PojavLauncherTeam/PojavLauncher, this is the website
