### ISSUE TITLE
Unsupported Mods Page Still Out of Date

### ISSUE THREAD

**Issue by Renegade4339** [PojavLauncherTeam/pojavlauncherteam.github.io#140]
The [page](https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html#unsupported-clients) still doesn't work for whatever reason. As the last updated is back in April 4, 2023. I made an update in the branch but the changes I put doesn't show up in the page.

**Comment by GaucovyAero** [comment]
i contacted the person thats accountable for this but i got no response :/

**Comment by mchnjt** [comment]
:/

**Comment by mchnjt** [comment]
*cough* could've fixed the issue if i can put my stuff on the repo
![Screenshot_2024_0416_153236](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/assets/83752061/2935a5d7-622a-403e-b253-aef29639099e)
(this is me btw)
