### ISSUE TITLE
About avaritia mod

### ISSUE THREAD

**Issue by Anasui404** [PojavLauncherTeam/pojavlauncherteam.github.io#144]
When I use avaritia mod,my game was broken,if I delete this mod,my game can work,why?

**Comment by ITLSupress** [comment]
Wrong repo according to this post.
https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/issues/73

Recommend this instead.
https://github.com/PojavLauncherTeam/PojavLauncher/issues
