### ISSUE TITLE
Can't connect to the server 

### ISSUE THREAD

**Issue by Pumkinslash** [PojavLauncherTeam/pojavlauncherteam.github.io#147]
When I start my server and try to connect it it says can't connect to the server.
![Screenshot_2024-05-15-10-55-47-87_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/assets/112311145/105e46fa-46b5-4543-9e5c-a7d97b1b5cc1)

**Comment by mchnjt** [comment]
Please move your issue on the [Android repo.](https://github.com/PojavLauncherTeam/PojavLauncher)
