### ISSUE TITLE
[Bug] [Sign in]

### ISSUE THREAD

**Issue by BlazeIsDazed** [PojavLauncherTeam/pojavlauncherteam.github.io#148]
I own bedrock and Java on PC… Signing in keeps me stuck on demo so I can’t play. RIP

**Comment by truong2983** [comment]
![Uploading CB0E734A-9767-4B1B-BD14-CE3FEB9702AB.png…]()

**Comment by mchnjt** [comment]
Please move your issue on the [Android repo.](https://github.com/PojavLauncherTeam/PojavLauncher)

**Comment by BlazeIsDazed** [comment]
I’m on iPhone not android

**Comment by kiokori-git** [comment]
then please proceed to move to the [iOS repo.](https://github.com/PojavLauncherTeam/PojavLauncher_iOS)
