### ISSUE TITLE
It has an error logging in to the internal account

### ISSUE THREAD

**Issue by truong2983** [PojavLauncherTeam/pojavlauncherteam.github.io#150]

**Comment by truong2983** [comment]
![Uploading A6E74BA8-5C7F-429D-85DF-46B0D7643CA7.png…]()

**Comment by truong2983** [comment]
Help

**Comment by truong2983** [comment]
It has an error logging in to the internal account

**Comment by truong2983** [comment]
Nnn

**Comment by truong2983** [comment]
![Uploading C2116854-652E-4819-AAFA-890EC6B66A49.png…]()

**Comment by mchnjt** [comment]
Please move your issue on the [Android repo.](https://github.com/PojavLauncherTeam/PojavLauncher)
