### ISSUE TITLE
Shift+W =F11 on keyboard?

### ISSUE THREAD

**Issue by tahiinpekmez** [PojavLauncherTeam/pojavlauncherteam.github.io#151]
hi im user of pojavlauncher on Android. im playing minecraft with keyboard and mause. my favorite game bedwars on hypixel. but there is a problem. when im bridging or whatever anytime i press shift+w converts the game from full screen to windowed. and i always die because it distracts me. if there is something that can be fixed, how do i fix it? or if it is something that cannot be done manually in Android, please fix it in the next update. thanks dear pojavlauncher team

**Comment by mchnjt** [comment]
Please move your issue on the [Android repo.](https://github.com/PojavLauncherTeam/PojavLauncher)
