### ISSUE TITLE
JIT issue

### ISSUE THREAD

**Issue by NotReal003** [PojavLauncherTeam/pojavlauncherteam.github.io#152]
Hello Pojav Team!

I have iOS 17.4 and I was looking for how I can enable JIT, the issue is idh mac or pc. And when will pojav be available at the app store?

**Comment by ItAnthon** [comment]
depending on what you have, you have to enable JIT in a different way. do you have a mac or a PC?

furthermore PojavLauncher will never be on the app store unless apple changes their rules about JIT.

**Comment by mchnjt** [comment]
Move this issue on the [iOS repo.](https://github.com/PojavLauncherTeam/PojavLauncher_iOS)
