### ISSUE TITLE
Can't launch Minecraft 1.21 pre release 1

### ISSUE THREAD

**Issue by Franek-ob** [PojavLauncherTeam/pojavlauncherteam.github.io#153]
Hello. I can’t launch version Minecraft 1.21 pre release 1, but I can launch version 24w21b. It crashes before MOJANG studios logo. 
I added my latestlog.txt as attachment. 
[latestlog.txt](https://github.com/user-attachments/files/15509252/latestlog.txt)

**Comment by Franek-ob** [comment]
CANtrun pre 2 and 3 too.

**Comment by GaucovyAero** [comment]
wrong repository, go to PojavLauncherTeam/PojavLauncher
