### ISSUE TITLE
Compatible mode suddenly is not compatible. 

### ISSUE THREAD

**Issue by Ion00000** [PojavLauncherTeam/pojavlauncherteam.github.io#156]
If you put both the fabric launcher, mode menu, and fabric API in the mode file and run it, it will not fall off the black screen.   
 I am using the current version 1.20.4.
 The fabric launcher used the latest version and the api used 1.20.4 
Mode menu also used 1.20.4 version 

"[main/INFO]:Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!"
 
I put it in the mode file and checked the version of each mode, but I don't know how to solve this because there is an incompatible mode as written above.

**Comment by kiokori-git** [comment]
wrong repo, proceed to the android repo please

**Comment by Ion00000** [comment]
It has not been resolved. 
I put it in the mode file in Minecraft in the Android file, but the same phenomenon is still appearing.

**Comment by kiokori-git** [comment]
i just said proceed to the android repo, create an issue there, not here.

**Comment by Ion00000** [comment]
Android > data > net.kdt.pojavlaunch > files > minecraft > mods 
Is this the file path?

**Comment by kiokori-git** [comment]
i just said proceed to the android repo, create an issue there, not here. i just said proceed to the android repo, create an issue there, not here. i just said proceed to the android repo, create an issue there, not here. i just said proceed to the android repo, create an issue there, not here. i just said proceed to the android repo, create an issue there, not here. i just said proceed to the android repo, create an issue there, not here. i just said proceed to the android repo, create an issue there, not here. i just said proceed to the android repo, create an issue there, not here. i just said proceed to the android repo, create an issue there, not here.i just said proceed to the android repo, create an issue there, not here.

**Comment by Isokaz** [comment]
Mode or mods?
