### ISSUE TITLE
Android 14 Mouse doesn't Work

### ISSUE THREAD

**Issue by kenshidoko** [PojavLauncherTeam/pojavlauncherteam.github.io#161]
Android 14 has been officially updated, the mouse has change, I use a Physical Mouse and Keyboard to play Pojav and I have some problems. The mouse doesn't work anymore, Physical mouse on android 14 is not connected to the virtual mouse, they are completely separated.

**Comment by GaucovyAero** [comment]
wrong repository, go to PojavLauncherTeam/PojavLauncher, be sure to also say your device model
