### ISSUE TITLE
Problem with links

### ISSUE THREAD

**Issue by Wumisk** [PojavLauncherTeam/pojavlauncherteam.github.io#162]
When you open a link in a running game, it sends you to Google calendar.  please make the links open in your browser (chrome, opera, firefox)

**Comment by SpaceSoldier123** [comment]
Just copy to clipboard and paste it in manually

**Comment by SpaceSoldier123** [comment]
Btw this issue should probably be on a different repo

**Comment by SpaceSoldier123** [comment]
It should be here: https://github.com/PojavLauncherTeam/PojavLauncher

(https://github.com/PojavLauncherTeam/PojavLauncher_iOS for iOS)

**Comment by kiokori-git** [comment]
> It should be here: https://github.com/PojavLauncherTeam/PojavLauncher
> 
> (https://github.com/PojavLauncherTeam/PojavLauncher_iOS for iOS)

correct
