### ISSUE TITLE
Login into Microsoft account doesn't work

### ISSUE THREAD

**Issue by VIPProGamerPlag** [PojavLauncherTeam/pojavlauncherteam.github.io#164]
I can't login to my Microsoft account, it keep saying that " ![Screenshot_20240622_062453](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/assets/95624703/8696fd0e-da97-4c42-b08a-38a8f6278a5b) "
Please Tell me what to do with this problem

**Comment by VIPProGamerPlag** [comment]
And yes I did make a Minecraft Profile

**Comment by kiokori-git** [comment]
wrong repo, go to the android repo

**Comment by VIPProGamerPlag** [comment]
> wrong repo, go to the android repo

What's a repo?

**Comment by kiokori-git** [comment]
> > wrong repo, go to the android repo
> 
> What's a repo?

this place is a repo's issue

**Comment by VIPProGamerPlag** [comment]
> > > wrong repo, go to the android repo
> > 
> > 
> > What's a repo?
> 
> this place is a repo's issue

Ohh ok where to find android repo?

**Comment by kiokori-git** [comment]
> > > > wrong repo, go to the android repo
> > > 
> > > 
> > > What's a repo?
> > 
> > 
> > this place is a repo's issue
> 
> Ohh ok where to find android repo?

https://github.com/PojavLauncherTeam/PojavLauncher

**Comment by VIPProGamerPlag** [comment]
> > > > > wrong repo, go to the android repo
> > > > 
> > > > 
> > > > What's a repo?
> > > 
> > > 
> > > this place is a repo's issue
> > 
> > 
> > Ohh ok where to find android repo?
> 
> https://github.com/PojavLauncherTeam/PojavLauncher

tysm
