### ISSUE TITLE
Physical mouse and keyboard issue in New Update

### ISSUE THREAD

**Issue by webdev-ahad** [PojavLauncherTeam/pojavlauncherteam.github.io#165]
Hey Pojav Launcher Team! 
So basically we have problem using physical mouse and keyboard in latest updates please if you are reading this kindly fix this problem or if there is new option for keyboard and mouse so please let us know

**Comment by SammMC860** [comment]
Same

**Comment by KKJUAO** [comment]
Eles tem que arrumar logo tô a 2dias sem jogar

**Comment by minecraftfan7** [comment]
Physical mouse and keyboard works for me

**Comment by kiokori-git** [comment]
wrong repo, go to the android repo
