### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SammMC860** [PojavLauncherTeam/pojavlauncherteam.github.io#169]
Hey PojavLauncher Team! Please fix my mouse, when I play Pojav Launcher I use the mouse and keyboard when I start the mouse my cursor doesn't appear and the Pojav Launcher cursor doesn't work. Update FoxGlove Version, When I use EdelWeis my mouse works, but my cursor is black

My Device : 
Oppo A5 2020
Android 11
Snapdragon 665

**Comment by kiokori-git** [comment]
wrong repo, go to the android repo
