### ISSUE TITLE
forced mouse on chromebook

### ISSUE THREAD

**Issue by Eggzheads** [PojavLauncherTeam/pojavlauncherteam.github.io#171]
I've been using pojavlauncher for the past couple years and I've never seen this issue. When you launch the game it uses your Chromebook mouse as the cursor for the game instead of the virtual one, but now it uses the virtual one instead of your cursor.

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
