### ISSUE TITLE
Embeddium patch.

### ISSUE THREAD

**Issue by Miscepicademel** [PojavLauncherTeam/pojavlauncherteam.github.io#175]
Will we ever have a embeddium patch? Like the ones for Sodium and Rubidium? I managed to run Rubidium on 1.20.1 but it's a old version, not to mention how it doesn't support crucial optimization mods like Radium Reforged, which basically forces people with a mid-phone to backport since they'll get less than 30fps due to the Rubidium limitations.

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
