### ISSUE TITLE
the sec button

### ISSUE THREAD

**Issue by allavyazmin** [PojavLauncherTeam/pojavlauncherteam.github.io#176]
the sec button it doesn't work when i trying to place a block

https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/assets/139253274/7efcc543-a90a-48e9-a4d3-7ee602babe31

**Comment by Miscepicademel** [comment]
Seriously do you have a working braincell?

**Comment by rcoundon** [comment]
> Seriously do you have a working braincell?

Maybe suggesting why you think this isn't an issue would be more helpful than a personal insult. 

It's no wonder open source developers are burning out left, right and centre when they're working, on their own time, without pay, inside this kind of environment.

**Comment by Miscepicademel** [comment]
> > Seriously do you have a working braincell?
> 
> Maybe suggesting why you think this isn't an issue would be more helpful than a personal insult.
> 
> It's no wonder open source developers are burning out left, right and centre when they're working, on their own time, without pay, inside this kind of environment.

dude is basically failing the lacchoufee kids tool set and i need to be respectful? is that a bot response?

**Comment by rcoundon** [comment]
> > > Seriously do you have a working braincell?
> > 
> > 
> > Maybe suggesting why you think this isn't an issue would be more helpful than a personal insult.
> > It's no wonder open source developers are burning out left, right and centre when they're working, on their own time, without pay, inside this kind of environment.
> 
> dude is basically failing the lacchoufee kids tool set and i need to be respectful? is that a bot response?

Then there are more decent, respectful and helpful ways to point that out. 
And no, it's not a bot response, it's a response from someone who is rather tired of seeing this kind of behaviour in the open source community having worked in it, on and off, for nearly 20 years.

**Comment by allavyazmin** [comment]
> Seriously do you have a working braincell?

im so sorry about that. i want to delete this post, but idk how.

**Comment by allavyazmin** [comment]
im so sorry about that. i want to delete this post, but idk how.

**Comment by allavyazmin** [comment]
im so sorry about that. i want to delete this post, but idk how.
