### ISSUE TITLE
Pojavlaunch keeps crashing

### ISSUE THREAD

**Issue by Eggzheads** [PojavLauncherTeam/pojavlauncherteam.github.io#179]
if you've read my other posts it's related to that. Any version I launch now always crashes. I have once again reset my chromebook and instead of just 1.12+ not working it's every version now. I think it's something to do with the new "Game Dashboard" on google play apps for chromebooks which it tries to replicate clicks just by playing on mobile. Before all of this happened it was all fine until I tested the game dashboard. I have added the latestlog.txt file down below. Please help.
[latestlog.txt](https://github.com/user-attachments/files/16188897/latestlog.txt)

**Comment by GaucovyAero** [comment]
wrong repository, go to PojavLauncherTeam/PojavLauncher
