### ISSUE TITLE
1.7.10 crash bug

### ISSUE THREAD

**Issue by RiDDeR31** [PojavLauncherTeam/pojavlauncherteam.github.io#18]
Always when i enter 1.7.10 in normal,forge or optifine it always like crashes but sends me to the sing up part and not to the crash informarion

**Comment by ednellbasilio** [comment]
Hello how the forge 1.7.10 crash and exit code 1

**Comment by RiDDeR31** [comment]
What do you mean?

**Comment by ednellbasilio** [comment]
I said the forge are crash on forge but some render distance up 9+ that why
I said forge 1.12.2

**Comment by RiDDeR31** [comment]
But it crashes in the vanilla 1.7.10 too

**Comment by Doregon** [comment]
Not the correct repository to open an issue on, closing.
