### ISSUE TITLE
completely ruined mouse experience on android

### ISSUE THREAD

**Issue by DanSparrow** [PojavLauncherTeam/pojavlauncherteam.github.io#183]
Since the latest update, for some reason, it was decided to force the internal pojavauncher fake cursor whenever you use a mouse to play, overriding the default  android cursor, which completely ruins the experience because the virtual mouse doesn't work well, can't interact with the hub or with android buttons and has a completely different way to handle mouse sensitivity, does anyone know why would something like that be changed? worked perfectly before with the android default cursor, I don't see any advantage on changing it.

**Comment by GaucovyAero** [comment]
wrong repository, go to PojavLauncherTeam/PojavLauncher
