### ISSUE TITLE
Ability To Add Textures To Touch Controls

### ISSUE THREAD

**Issue by Luminousquestor** [PojavLauncherTeam/pojavlauncherteam.github.io#190]
Can you implement a way to add textures to the touch controls? I'll include an image showcasing this idea.
 
![Untitled1274_20240805171315](https://github.com/user-attachments/assets/c1ecb1b7-2a62-468d-aa2c-1cad320b8d26)

**Comment by kiokori-git** [comment]
great suggestion, though this actually has been suggested once, but sadly we won't likely implement it due to high memory (RAM) usage.

**Comment by kiokori-git** [comment]
and also, you're on the wrong repository, refer to the [android repo](https://github.com/PojavLauncherTeam/PojavLauncher).
