### ISSUE TITLE
What to do? Error -1 

### ISSUE THREAD

**Issue by IskanderBaigildin** [PojavLauncherTeam/pojavlauncherteam.github.io#204]
![Screenshot_20241003-202622](https://github.com/user-attachments/assets/894ee242-eb4f-4c19-bcd8-46fd11ef4978)
![Screenshot_20241003-205149](https://github.com/user-attachments/assets/a892d042-12be-4685-ac0e-220f4d52ec51)
![Screenshot_20241003-205145](https://github.com/user-attachments/assets/d744f1c8-220a-43cf-abaf-a7a2abecc170)

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
