### ISSUE TITLE
Showing black screen in 24w40a

### ISSUE THREAD

**Issue by BNaise** [PojavLauncherTeam/pojavlauncherteam.github.io#205]
It black screen in 24w40a . You can still press the buttons.

https://github.com/user-attachments/assets/022852cd-f425-4535-b1c9-de76db864775

**Comment by gamdr** [comment]
i put my renderer on angle vulkan and it worked

**Comment by Aaayayayg** [comment]
plz

**Comment by gamdr** [comment]
im using a processor helio g 96

**Comment by Tucky143** [comment]
Can confirm

**Comment by Tucky143** [comment]
All versions on certain renderer

**Comment by BNaise** [comment]
It's happening in versions after that if this doesn't fix we could not play 1.21.2 and 1.22 in pojavlauncher in future.

**Comment by nagado** [comment]
Just had a similar issue, switching renders helped, but a less technical/determined person would not have found this and probably would give up instead. This issue might just be solved with a new default

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
