### ISSUE TITLE
GitHub not working

### ISSUE THREAD

**Issue by Ryanisawesome884** [PojavLauncherTeam/pojavlauncherteam.github.io#212]
Hey so when I was just login it in into my Microsoft account I used it and it stayed I need to reset it but then I saw the option sign in with GitHub I made an GitHub account I typed it in and it didn’t work it said: “This is a work or school account.“when it’s not
Pls help

**Comment by GaucovyAero** [comment]
Não estou conseguindo entra na minha conta da Microsoft não és indo por favor me ajude

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher (i copied bad text inb4)
