### ISSUE TITLE
Add More in Java Tweaks Settings

### ISSUE THREAD

**Issue by mZiyadhbinismail** [PojavLauncherTeam/pojavlauncherteam.github.io#217]
![Screenshot_2024-11-23-22-26-35-52_67a64f1fc1b88908dad3392f76c1969b](https://github.com/user-attachments/assets/05a64020-5b42-4d02-ab05-56a857ed3c7a)

**Comment by mZiyadhbinismail** [comment]
See this Category Settings is Too small! please Add More

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
