### ISSUE TITLE
Put the mods into folder but it does not load

### ISSUE THREAD

**Issue by GodOfFEED** [PojavLauncherTeam/pojavlauncherteam.github.io#223]
![Screenshot_2024-11-29-23-50-29-283_net kdt pojavlaunch](https://github.com/user-attachments/assets/2f7cc901-1fbd-4627-a370-5b5d8787b1b7)
![Screenshot_2024-11-29-23-50-51-100_ru zdevs zarchiver](https://github.com/user-attachments/assets/13e386b7-908e-4948-ad7a-f1c9a622498e)

**Comment by Zahar2loshara** [comment]
Man its the wrong place to post issue, its 'bout the site, not the app it self

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
