### ISSUE TITLE
Can't link the microsoft account?

### ISSUE THREAD

**Issue by PhyTony1** [PojavLauncherTeam/pojavlauncherteam.github.io#227]
I have Minecraft Java version in my account but I can't log in to the launcher with that account. I bought Minecraft Launcher and Minecraft Java & Bedrock from Xbox App.

When I wanted to login however, the launcher said that I do not own Minecraft?

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
