### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by xCROYSx** [PojavLauncherTeam/pojavlauncherteam.github.io#230]
Hello!
Textures disappear when a meteorite from ae2 is found, presumably. It only helps to restart on another visualizer and leave the field of view.
Modpack Jacon Ex Machina, downloaded from Curse.
Also in the Clouds of Darkness modpack, also downloaded from Curse, when I install something from ae2, textures disappear. It only helps to restart on another visualizer and remove the supplied block.
Vivo T1 phone, Holy GL4ES visualizer.
There is no such problem on Zink, but it is very slow.
![Screenshot_20241228_120057_net kdt pojavlaunch](https://github.com/user-attachments/assets/fc1be63a-b795-439c-b801-9a50ab738f31)
[latestlog.txt](https://github.com/user-attachments/files/18265699/latestlog.txt)

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher
