### ISSUE TITLE
Custom version crashing

### ISSUE THREAD

**Issue by MinecraftMikey20** [PojavLauncherTeam/pojavlauncherteam.github.io#43]
Hi there! I made my own Minecraft client but it doesn't seem to work, I put it in the version folder with the required files and everything should work, because on windows and mac it does, but when I tried starting it on pojav launcher, it keeps crashing, it's not an .exe but a 
.jar and a .rar in a folder, does anyone know why this keeps happening?

**Comment by artdeell** [comment]
issue on wrong repository, move it please

**Comment by MinecraftMikey20** [comment]
> 

Where do I have to put it then?

**Comment by artdeell** [comment]
> > 
> 
> Where do I have to put it then?

https://github.com/PojavLauncherTeam/PojavLauncher
