### ISSUE TITLE
Can anyone build for me 1.4.6 forge

### ISSUE THREAD

**Issue by Presx2FForRespect** [PojavLauncherTeam/pojavlauncherteam.github.io#46]
Can anyone build for me 1.4.6 forge
I have tried all the solutions to my problem, but there is no solution. The problem is that after I do some steps to install forge
the original version is downloaded without forge.

**Comment by mchnjt** [comment]
Ths issues tab for this repository is not for reporting launcher bugs. Please move your issue on [the actual repo](https://github.com/pojavlauncherteam/pojavlauncher/issues).
