### ISSUE TITLE
Screen minimizes when shift+w

### ISSUE THREAD

**Issue by kvfs2k07** [PojavLauncherTeam/pojavlauncherteam.github.io#59]
Hello, I connect my mouse & keyboard to my mobile and when I press Shift+W it togglea fullscreen. I don't know if this is a feature or a bug, but I'd like get rid of it because it so annoying when I'm shifting and going forward at the same time.

**Comment by mchnjt** [comment]
Please transfer your issue on [PojavLauncherTeam/PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher). This repository's issue tab is not for this purpose.
