### ISSUE TITLE
Some Buttons will randomly stop working

### ISSUE THREAD

**Issue by Avrage-user** [PojavLauncherTeam/pojavlauncherteam.github.io#60]
I am using an Xbox controller randomly my place and break, which is LT and RT will randomly stop working I know it isn’t the controller because I have connected it to my Xbox and it is perfectly fine then when I try to place or break with the mobile controls, sometimes they will randomly stop working and I have to restart the app

**Comment by mchnjt** [comment]
![IMG_20230502_131701](https://user-images.githubusercontent.com/83752061/236363114-3756e185-1cf6-4dd5-be01-47a9964c14a1.jpg)
