### ISSUE TITLE
Silly question about console support

### ISSUE THREAD

**Issue by vico93** [PojavLauncherTeam/pojavlauncherteam.github.io#62]
Is there any chance we could see this launcher adapted to run ou Playstation 4/5 consoles?

If not, is there any alternative to run MC Java on those consoles?

**Comment by mchnjt** [comment]
Damn why do people mistake that this is the pojav repo

**Comment by NotAHero04** [comment]
> Damn why do people mistake that this is the pojav repo

Disable Issues on this repo eta

**Comment by vico93** [comment]
Strange, i really thought i opened this issue on the other repo. Sorry.
