### ISSUE TITLE
When?

### ISSUE THREAD

**Issue by frenda7** [PojavLauncherTeam/pojavlauncherteam.github.io#64]
When 1.20 pre7?

**Comment by Paindeluxe** [comment]
My man, it's already available

**Comment by frenda7** [comment]
![Screenshot_20230530-110617](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/assets/76841954/7bfd6a13-f174-447d-b59b-b257c19ba1a3)
(Moscow Time)

**Comment by frenda7** [comment]
Okay, I've solved the problem. On another phone, the new version is displayed. idk why I don't have it.
