### ISSUE TITLE
Can't enable JIT with alt store 

### ISSUE THREAD

**Issue by kolya009** [PojavLauncherTeam/pojavlauncherteam.github.io#65]
Whenever I try to use "JIT" with ProjavLauncher + AltStore/AltServer I get an error saying 

" - AltServer.DeveloperDiskError 0

  - Error Description
  The URL to download the Developer disk image could not be determined.
  - Failure Reason
  The URL to download the Developer disk image could not be determined.

"

**Comment by mchnjt** [comment]
Wrong repo.
