### ISSUE TITLE
bug!

### ISSUE THREAD

**Issue by computer1234** [PojavLauncherTeam/pojavlauncherteam.github.io#68]
When the game recognizes the CPU， Can lead to a decrease in device performance

**Comment by Noth-Shian** [comment]
Pls leave more info, how does the game recognizes the CPU? it happends in at the start of the game? when loading chunks in a world?

**Comment by computer1234** [comment]
That is, the number of CPU cores displayed on the left side of the debugging screenAll images were captured just after entering the game

---Original---
From: ***@***.***&gt;
Date: Wed, Jun 14, 2023 03:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PojavLauncherTeam/pojavlauncherteam.github.io] bug! (Issue #68)




 
Pls leave more info, how does the game recognizes the CPU? it happends in at the start of the game? when loading chunks in a world?
