### ISSUE TITLE
Error exiting the game when entering the map 

### ISSUE THREAD

**Issue by yamate510** [PojavLauncherTeam/pojavlauncherteam.github.io#79]
there is a bug that causes me to exit the game when I enter the map

**Comment by alexytomi** [comment]
send latest.log

**Comment by yamate510** [comment]
https://drive.google.com/file/d/18JMFxcztGCU7r2BBGPqAwch5g9Uqo8-v/view?usp=drivesdk
sorry but i can only share by drive

**Comment by mchnjt** [comment]
#73.
