### ISSUE TITLE
Persistent Anti-Cheat Kicks for Players on Launcher - Integration with Floodgate Plugin Suggested

### ISSUE THREAD

**Issue by DimaSergeew** [PojavLauncherTeam/pojavlauncherteam.github.io#86]
Hello,

I am encountering a recurring issue with players who are using my server through a specific launcher – they are consistently being kicked by the anti-cheat system. This issue is not present for players who are using the PC version of the game. I kindly request assistance in addressing this matter. One potential solution could be establishing integration with the Floodgate plugin. This integration could classify these launcher-based players as "Bedrock" users and exempt them from the anti-cheat verification. Alternatively, I am open to exploring other approaches that could mitigate the problem of false positive kicks triggered by the anti-cheat system on this launcher, affecting players using various anti-cheat clients.

Thank you for your attention to this issue. Your support in resolving this matter and enhancing the gameplay experience for all players would be greatly appreciated. If additional information is required or if there are further suggestions, please don't hesitate to reach out.

**Comment by GaucovyAero** [comment]
Wrong repository, this is the website. Post this issue into PojavLauncherTeam/PojavLauncher instead please.
