### ISSUE TITLE
Selected Runtime Broken

### ISSUE THREAD

**Issue by DavidOJChapman** [PojavLauncherTeam/pojavlauncherteam.github.io#88]
![Screenshot_20230816-041938_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/assets/142371020/7f6e56e9-2ac5-4aea-9a8c-5e6fd9edacd9)
Hi, I am trying to install forge 1.20.1 but whenever I chose the Jar the message 'selected runtime broken' what does this mean and how can I fix it.

**Comment by GaucovyAero** [comment]
wrong repository, repost in PojavLauncherTeam/PojavLauncher instead
