### ISSUE TITLE
Pixelmon reforged 9.2.2 (1.20.1) not working

### ISSUE THREAD

**Issue by ItsMythKing** [PojavLauncherTeam/pojavlauncherteam.github.io#93]
I launched Pixelmon 9.2.2 and it crashes every time I changed the settings in config.yml to turn the discord off and still crashes and I try to install the mod "not enough crashes" so it won't crash anymore but the font is buged instead of numbers and letters it's all squares

**Comment by Bel69420** [comment]
Send latestlog

**Comment by Bel69420** [comment]
Without using not enough crash mod

**Comment by GaucovyAero** [comment]
wrong repository, go to PojavLauncherTeam/PojavLauncher
