### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by Maksimmansorii** [PojavLauncherTeam/pojavlauncherteam.github.io#94]
https://drive.google.com/file/d/1i3jm0u-F5UMXAHeRT6SenZ1fg_Lc_Qo_/view?usp=drivesdk
hello, I decided to download the launcher to the tablet, I run minecraft, an error pops up, how to fix it

**Comment by s1QE1278** [comment]
Help me understand what mod is causing the game to crash?
[crash-2023-09-21_20.21.22-client.txt](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/files/12689603/crash-2023-09-21_20.21.22-client.txt)

**Comment by GaucovyAero** [comment]
wrong repo, go to pojavlauncherteam/pojavlauncher instead
