### ISSUE TITLE
Unable to connect Microsoft Account 

### ISSUE THREAD

**Issue by conttdj** [PojavLauncherTeam/pojavlauncherteam.github.io#97]
![Screenshot_2023-10-04-21-52-26-24_bab8561a5f94f0a53956d8cbbeaad774.jpg](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/assets/112465867/46432729-4651-4782-a96f-9e966d954396)

Basically it's stuck at 75% and not able to connect at all, I do not think it's a problem on my side, maybe you guys could take a look into this

**Comment by GaucovyAero** [comment]
wrong repo, go to pojavlauncherteam/pojavlauncher instead
